name: Generate Snake

# Run workflow every 6 hours
on:
  schedule:
      - cron: "0 */6 * * *"

# Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

# Job definition
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the contribution grid snake
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-snake.svg

      # Upload the contribution grid snake to the repository
      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/github-snake.svg
